<?php

namespace App\Http\Controllers\Api;

use App\Services\ClientService;

class ClientController extends AbstractController
{
    protected $clientService;

    public function __construct(ClientService $clientService)
    {
        $this->clientService = $clientService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $clients = $this->clientService->all();
        return $clients;
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $client = $this->clientService->find($id);
        return $client;
    }

    public function create()
    {
        return parent::create(); // TODO: Change the autogenerated stub
    }

    public function destroy($id)
    {
        $client = $this->clientService->delete($id);
        return $client;
    }
}
