<?php

namespace App\Http\Controllers\Api;

use App\Services\ContactService;

class ContactController extends AbstractController
{
    protected $service;

    public function __construct(ContactService $contactService)
    {
        $this->service = $contactService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $clients = $this->service->all();
        return $clients;
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $client = $this->service->find($id);
        return $client;
    }

    public function create()
    {
        return parent::create(); // TODO: Change the autogenerated stub
    }

    public function destroy($id)
    {
        $client = $this->service->delete($id);
        return $client;
    }
}
